
# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://192.168.0.100:3306/LAN_share?useUnicode=true&characterEncoding=UTF-8
#     username: root
#     password: pzw123456
spring:
  datasource:
    url: jdbc:h2:~/share
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  # h2:
  #   console:
  #     settings:
  #       web-allow-others: true
  #     path: /h2-console
  #     enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024000000000MB
      max-request-size: 1024000000000MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  http2:
    enabled: true
  port: 8081
